// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Uho8w78VJjcNiNdPgdi4440NyoubFHs',
    appId: '1:166006694890:web:eabffd86c484319973c893',
    messagingSenderId: '166006694890',
    projectId: 'tramber-217c4',
    authDomain: 'tramber-217c4.firebaseapp.com',
    storageBucket: 'tramber-217c4.appspot.com',
    measurementId: 'G-60ZZXRYHNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHRDZc2zYhQ67swMAzN_X193Z97TbEhM',
    appId: '1:166006694890:android:8637ad87c9b667a673c893',
    messagingSenderId: '166006694890',
    projectId: 'tramber-217c4',
    storageBucket: 'tramber-217c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpWdPjurRJJpIk-DHLaSoNHkZLCwHRNQ',
    appId: '1:166006694890:ios:26e19230c41a612a73c893',
    messagingSenderId: '166006694890',
    projectId: 'tramber-217c4',
    storageBucket: 'tramber-217c4.appspot.com',
    iosBundleId: 'com.example.tramber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpWdPjurRJJpIk-DHLaSoNHkZLCwHRNQ',
    appId: '1:166006694890:ios:90f48f6c9779014573c893',
    messagingSenderId: '166006694890',
    projectId: 'tramber-217c4',
    storageBucket: 'tramber-217c4.appspot.com',
    iosBundleId: 'com.example.tramber.RunnerTests',
  );
}
